name: 'anyone-validate-fs'
author: 'Zhang Nan (zhang_nan_163@163.com)'
branding:
  icon: user-check
  color: white
description: 'Validate repository file structure as we expected'
inputs:
  brace-expansion:  
    description: 'brace-expansion of expected directory structure'
    required: true
    default: ''
  ignore-files:  
    description: 'the files you want to ignore. split with comma.'
    required: false
    default: ''
  ignore-directories:  
    description: 'the directories you want to ignore. split with comma.'
    required: false
    default: ''
  read-path:
    description: 'the path that you assign to read.'
    required: false
    default: ''
  render-layout:
    description: 'render diff result with "vertical" or "horizontal"'
    required: false
    default: 'vertical'
outputs:
  output:
    description: 'output of execution'
runs:
  using: 'node12'
  main: 'dist/index.js'
